[project]
name = "aoe2de-flat-tree"
version = "0.1.0"
description = "Generate uniform cube tree graphics and an AoE2DE local mod"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "numpy>=2.5.3",
    "pillow>=12.3.0",
]

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
    "matplotlib>=3.11.2",
]
